[workspace]
resolver = "2"
members = [
    "day_01_historian_hysteria",
    "day_02_rednosed_reports",
    "day_03_mull_it_over",
    "day_04_ceres_search",
    "day_05_print_queue",
    "day_06_guard_gallivant",
    "day_07_bridge_repair",
    "day_08_resonant_collinearity"
]