[package]
name = "day_18_ram_run"
version = "0.1.0"
edition = "2021"

[dependencies]
advent-of-code = { git = "https://github.com/palcoo42/advent-of-code.git", tag = "4.1.3" }
priority-queue = { version = "2.*.*" }