[package]
name = "day_03_mull_it_over"
version = "0.1.0"
edition = "2021"

[dependencies]
advent-of-code = { git = "https://github.com/palcoo42/advent-of-code.git", tag = "3.0.0" }
regex = { version = "1.11.*" }